"""Tests for the Phase 13 evidence recorder.

Run from repo root:  python -m pytest scripts/__tests__/test_evidence_recorder.py
"""
from __future__ import annotations

import json

from scripts.evidence_recorder import (
    SCHEMA_VERSION,
    EvidenceRecord,
    verify_file,
    verify_record,
)

REQUIRED_KEYS = {
    "schema_version", "run_id", "work_package", "environment", "app_version",
    "commit_sha", "started_at", "finished_at", "command", "scenario",
    "preconditions", "assertions", "result", "metrics", "failure_details",
    "artifacts", "remaining_risks", "reviewer_notes", "content_sha256",
}


def _record(**over) -> EvidenceRecord:
    base = dict(
        work_package="WP-TEST",
        scenario="unit self-check",
        result="pass",
        command="python -m pytest tests/",
        assertions=["it works"],
        metrics={"passed": 3, "failed": 0},
    )
    base.update(over)
    return EvidenceRecord(**base)


def test_payload_has_all_required_fields():
    payload = _record().to_payload()
    assert REQUIRED_KEYS.issubset(payload.keys())
    assert payload["schema_version"] == SCHEMA_VERSION


def test_run_id_autogenerated_from_work_package():
    rec = _record(work_package="WP-02")
    assert rec.run_id.startswith("WP-02-")


def test_digest_verifies_and_detects_tampering():
    payload = _record().to_payload()
    assert verify_record(payload) is True
    # Mutating any field must break the digest.
    payload["result"] = "fail"
    assert verify_record(payload) is False


def test_write_emits_json_and_markdown(tmp_path):
    paths = _record().write(tmp_path)
    assert paths["json"].endswith(".json")
    assert paths["markdown"].endswith(".md")
    on_disk = json.loads(open(paths["json"], encoding="utf-8").read())
    assert on_disk["result"] == "pass"
    assert verify_file(paths["json"]) is True
    md = open(paths["markdown"], encoding="utf-8").read()
    assert "unit self-check" in md
    assert "PASS" in md


def test_recorder_does_not_capture_arbitrary_env(monkeypatch):
    # A secret in the environment must never appear in the record.
    monkeypatch.setenv("OPENAI_API_KEY", "sk-should-not-be-captured")
    blob = json.dumps(_record().to_payload())
    assert "sk-should-not-be-captured" not in blob
